/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as AppProductsRouteRouteImport } from './routes/app/products/route'
import { Route as AppOrdersRouteRouteImport } from './routes/app/orders/route'
import { Route as TestCartIndexRouteImport } from './routes/test/cart/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppOrdersIndexRouteImport } from './routes/app/orders/index'
import { Route as AppFaqsIndexRouteImport } from './routes/app/faqs/index'
import { Route as AppCartIndexRouteImport } from './routes/app/cart/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AppProductIdRouteImport } from './routes/app/product/$id'
import { Route as AppOrderOrderIdRouteImport } from './routes/app/order/$orderId'
import { Route as AdminProductIdRouteImport } from './routes/admin/product/$id'
import { Route as AdminOrderOrderIdRouteImport } from './routes/admin/order/$orderId'
import { Route as AdminProductNewIndexRouteImport } from './routes/admin/product/new/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppProductsRouteRoute = AppProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersRouteRoute = AppOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const TestCartIndexRoute = TestCartIndexRouteImport.update({
  id: '/test/cart/',
  path: '/test/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrdersRouteRoute,
} as any)
const AppFaqsIndexRoute = AppFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCartIndexRoute = AppCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppProductIdRoute = AppProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrderOrderIdRoute = AppOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminProductIdRoute = AdminProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrderOrderIdRoute = AdminOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductNewIndexRoute = AdminProductNewIndexRouteImport.update({
  id: '/product/new/',
  path: '/product/new/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/orders': typeof AppOrdersRouteRouteWithChildren
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/auth/admin': typeof AuthAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/order/$orderId': typeof AdminOrderOrderIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/app/cart/': typeof AppCartIndexRoute
  '/app/faqs/': typeof AppFaqsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/test/cart/': typeof TestCartIndexRoute
  '/admin/product/new/': typeof AdminProductNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/admin': typeof AuthAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/order/$orderId': typeof AdminOrderOrderIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/app/cart': typeof AppCartIndexRoute
  '/app/faqs': typeof AppFaqsIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/test/cart': typeof TestCartIndexRoute
  '/admin/product/new': typeof AdminProductNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/orders': typeof AppOrdersRouteRouteWithChildren
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/auth/admin': typeof AuthAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/order/$orderId': typeof AdminOrderOrderIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/app/cart/': typeof AppCartIndexRoute
  '/app/faqs/': typeof AppFaqsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/test/cart/': typeof TestCartIndexRoute
  '/admin/product/new/': typeof AdminProductNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/orders'
    | '/app/products'
    | '/auth/admin'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/admin/'
    | '/app/'
    | '/admin/order/$orderId'
    | '/admin/product/$id'
    | '/app/order/$orderId'
    | '/app/product/$id'
    | '/admin/categories/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/app/cart/'
    | '/app/faqs/'
    | '/app/orders/'
    | '/app/products/'
    | '/app/profile/'
    | '/test/cart/'
    | '/admin/product/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/admin'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/admin'
    | '/app'
    | '/admin/order/$orderId'
    | '/admin/product/$id'
    | '/app/order/$orderId'
    | '/app/product/$id'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/app/cart'
    | '/app/faqs'
    | '/app/orders'
    | '/app/products'
    | '/app/profile'
    | '/test/cart'
    | '/admin/product/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/orders'
    | '/app/products'
    | '/auth/admin'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/admin/'
    | '/app/'
    | '/admin/order/$orderId'
    | '/admin/product/$id'
    | '/app/order/$orderId'
    | '/app/product/$id'
    | '/admin/categories/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/app/cart/'
    | '/app/faqs/'
    | '/app/orders/'
    | '/app/products/'
    | '/app/profile/'
    | '/test/cart/'
    | '/admin/product/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  TestCartIndexRoute: typeof TestCartIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/test/cart/': {
      id: '/test/cart/'
      path: '/test/cart'
      fullPath: '/test/cart/'
      preLoaderRoute: typeof TestCartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppOrdersRouteRoute
    }
    '/app/faqs/': {
      id: '/app/faqs/'
      path: '/faqs'
      fullPath: '/app/faqs/'
      preLoaderRoute: typeof AppFaqsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cart/': {
      id: '/app/cart/'
      path: '/cart'
      fullPath: '/app/cart/'
      preLoaderRoute: typeof AppCartIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/product/$id': {
      id: '/app/product/$id'
      path: '/product/$id'
      fullPath: '/app/product/$id'
      preLoaderRoute: typeof AppProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/order/$orderId': {
      id: '/app/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/app/order/$orderId'
      preLoaderRoute: typeof AppOrderOrderIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/product/$id': {
      id: '/admin/product/$id'
      path: '/product/$id'
      fullPath: '/admin/product/$id'
      preLoaderRoute: typeof AdminProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/order/$orderId': {
      id: '/admin/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/admin/order/$orderId'
      preLoaderRoute: typeof AdminOrderOrderIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product/new/': {
      id: '/admin/product/new/'
      path: '/product/new'
      fullPath: '/admin/product/new/'
      preLoaderRoute: typeof AdminProductNewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrderOrderIdRoute: typeof AdminOrderOrderIdRoute
  AdminProductIdRoute: typeof AdminProductIdRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductNewIndexRoute: typeof AdminProductNewIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminOrderOrderIdRoute: AdminOrderOrderIdRoute,
  AdminProductIdRoute: AdminProductIdRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductNewIndexRoute: AdminProductNewIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppOrdersRouteRouteChildren {
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppOrdersRouteRouteChildren: AppOrdersRouteRouteChildren = {
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppOrdersRouteRouteWithChildren = AppOrdersRouteRoute._addFileChildren(
  AppOrdersRouteRouteChildren,
)

interface AppProductsRouteRouteChildren {
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteRouteChildren: AppProductsRouteRouteChildren = {
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteRouteWithChildren =
  AppProductsRouteRoute._addFileChildren(AppProductsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppOrdersRouteRoute: typeof AppOrdersRouteRouteWithChildren
  AppProductsRouteRoute: typeof AppProductsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppOrderOrderIdRoute: typeof AppOrderOrderIdRoute
  AppProductIdRoute: typeof AppProductIdRoute
  AppCartIndexRoute: typeof AppCartIndexRoute
  AppFaqsIndexRoute: typeof AppFaqsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrdersRouteRoute: AppOrdersRouteRouteWithChildren,
  AppProductsRouteRoute: AppProductsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppOrderOrderIdRoute: AppOrderOrderIdRoute,
  AppProductIdRoute: AppProductIdRoute,
  AppCartIndexRoute: AppCartIndexRoute,
  AppFaqsIndexRoute: AppFaqsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  TestCartIndexRoute: TestCartIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
