/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppProductsRouteRouteImport } from './routes/app/products/route'
import { Route as AppOrdersRouteRouteImport } from './routes/app/orders/route'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppOrdersIndexRouteImport } from './routes/app/orders/index'
import { Route as AppCartIndexRouteImport } from './routes/app/cart/index'
import { Route as AppProductIdRouteImport } from './routes/app/product/$id'
import { Route as AppOrderOrderIdRouteImport } from './routes/app/order/$orderId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppProductsRouteRoute = AppProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersRouteRoute = AppOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrdersRouteRoute,
} as any)
const AppCartIndexRoute = AppCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductIdRoute = AppProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrderOrderIdRoute = AppOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/orders': typeof AppOrdersRouteRouteWithChildren
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/app/cart': typeof AppCartIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/app/cart': typeof AppCartIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/orders': typeof AppOrdersRouteRouteWithChildren
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/order/$orderId': typeof AppOrderOrderIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/app/cart/': typeof AppCartIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/orders'
    | '/app/products'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/app/order/$orderId'
    | '/app/product/$id'
    | '/app/cart'
    | '/app/orders/'
    | '/app/products/'
    | '/app/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/app'
    | '/app/order/$orderId'
    | '/app/product/$id'
    | '/app/cart'
    | '/app/orders'
    | '/app/products'
    | '/app/profile'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/orders'
    | '/app/products'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/app/order/$orderId'
    | '/app/product/$id'
    | '/app/cart/'
    | '/app/orders/'
    | '/app/products/'
    | '/app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppOrdersRouteRoute
    }
    '/app/cart/': {
      id: '/app/cart/'
      path: '/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/product/$id': {
      id: '/app/product/$id'
      path: '/product/$id'
      fullPath: '/app/product/$id'
      preLoaderRoute: typeof AppProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/order/$orderId': {
      id: '/app/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/app/order/$orderId'
      preLoaderRoute: typeof AppOrderOrderIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppOrdersRouteRouteChildren {
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppOrdersRouteRouteChildren: AppOrdersRouteRouteChildren = {
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppOrdersRouteRouteWithChildren = AppOrdersRouteRoute._addFileChildren(
  AppOrdersRouteRouteChildren,
)

interface AppProductsRouteRouteChildren {
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteRouteChildren: AppProductsRouteRouteChildren = {
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteRouteWithChildren =
  AppProductsRouteRoute._addFileChildren(AppProductsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppOrdersRouteRoute: typeof AppOrdersRouteRouteWithChildren
  AppProductsRouteRoute: typeof AppProductsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppOrderOrderIdRoute: typeof AppOrderOrderIdRoute
  AppProductIdRoute: typeof AppProductIdRoute
  AppCartIndexRoute: typeof AppCartIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrdersRouteRoute: AppOrdersRouteRouteWithChildren,
  AppProductsRouteRoute: AppProductsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppOrderOrderIdRoute: AppOrderOrderIdRoute,
  AppProductIdRoute: AppProductIdRoute,
  AppCartIndexRoute: AppCartIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
